const cron = require("node-cron")
const axios = require("axios")
const Quiz = require("../models/Quiz")
const Course = require("../models/Course")
const User = require("../models/User")
const mailSender = require("./mailSender")

/**
 * EduAI LMS — Sunday Quiz Scheduler
 * Developer: Samreet Kaur | AGC Amritsar
 * 
 * Runs every Sunday at 9:00 AM
 * Generates AI quizzes for all published courses
 * Sends email notification to enrolled students
 */

const generateQuestionsFromGemini = async (courseName, description, tags) => {
  try {
    const prompt = `Generate 5 multiple choice questions for a course called "${courseName}".
Course description: ${description}
Topics: ${tags?.join(", ") || courseName}

Return ONLY a valid JSON array with exactly this format, no extra text:
[
  {
    "question": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswer": 0,
    "explanation": "Brief explanation why this is correct"
  }
]

Rules:
- correctAnswer is the INDEX (0, 1, 2, or 3) of the correct option
- Make questions educational and relevant to the course
- Each question should have exactly 4 options
- Return exactly 5 questions`

    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${process.env.GEMINI_API_KEY}`,
      {
        contents: [{ role: "user", parts: [{ text: prompt }] }],
        generationConfig: { maxOutputTokens: 2000, temperature: 0.5 },
      },
      { headers: { "Content-Type": "application/json" } }
    )

    let text = response.data.candidates[0].content.parts[0].text
    text = text.replace(/```json/g, "").replace(/```/g, "").trim()
    return JSON.parse(text)
  } catch (error) {
    console.log("Gemini Error in Scheduler:", error?.response?.data || error.message)
    return null
  }
}

const getWeekNumber = () => {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 1)
  return Math.ceil((now - start) / (1000 * 60 * 60 * 24 * 7))
}

const runWeeklyQuizGeneration = async () => {
  console.log("🤖 [EduAI Quiz Scheduler] Starting Sunday quiz generation...")

  try {
    // Get all published courses
    const courses = await Course.find({ status: "Published" })
    console.log(`[Quiz Scheduler] Found ${courses.length} published courses`)

    let generated = 0
    let failed = 0

    for (const course of courses) {
      try {
        // Generate questions
        const questions = await generateQuestionsFromGemini(
          course.courseName,
          course.courseDescription,
          course.tag
        )

        if (!questions) {
          failed++
          continue
        }

        // Deactivate old quizzes for this course
        await Quiz.updateMany(
          { courseId: course._id },
          { isActive: false }
        )

        // Create new quiz
        const nextSunday = new Date()
        nextSunday.setDate(nextSunday.getDate() + 7)

        await Quiz.create({
          courseId: course._id,
          courseName: course.courseName,
          weekNumber: getWeekNumber(),
          questions,
          scheduledFor: nextSunday,
          isActive: true,
        })

        generated++
        console.log(`✅ Quiz generated for: ${course.courseName}`)

        // Send email to enrolled students
        if (course.studentsEnrolled && course.studentsEnrolled.length > 0) {
          const students = await User.find({
            _id: { $in: course.studentsEnrolled },
          }).select("email firstName")

          for (const student of students) {
            try {
              await mailSender(
                student.email,
                `🎯 Weekly Quiz Available — ${course.courseName}`,
                `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; background: #1a1a2e; color: white; border-radius: 10px;">
                  <div style="text-align: center; margin-bottom: 20px;">
                    <h1 style="color: #FFD700;">🤖 EduAI LMS</h1>
                    <h2 style="color: #FFD700;">Weekly Quiz is Ready!</h2>
                  </div>
                  <p>Hi ${student.firstName},</p>
                  <p>Your weekly AI-generated quiz for <strong style="color: #FFD700;">${course.courseName}</strong> is now available!</p>
                  <div style="background: #16213e; padding: 15px; border-radius: 8px; margin: 20px 0;">
                    <p>📚 <strong>Course:</strong> ${course.courseName}</p>
                    <p>❓ <strong>Questions:</strong> 5 MCQs</p>
                    <p>🤖 <strong>Generated by:</strong> EduAI (Gemini AI)</p>
                    <p>📅 <strong>Available:</strong> Every Sunday</p>
                  </div>
                  <p>Login to EduAI LMS and go to <strong>My Quizzes</strong> to attempt your quiz now!</p>
                  <div style="text-align: center; margin-top: 20px;">
                    <a href="http://localhost:3000/dashboard/my-quizzes" 
                       style="background: #FFD700; color: #000; padding: 12px 30px; border-radius: 5px; text-decoration: none; font-weight: bold;">
                      Take Quiz Now
                    </a>
                  </div>
        
                </div>
                `
              )
            } catch (emailErr) {
              console.log(`Email failed for ${student.email}:`, emailErr.message)
            }
          }
        }

        // Small delay to avoid API rate limit
        await new Promise((resolve) => setTimeout(resolve, 2000))
      } catch (courseErr) {
        console.log(`Failed for course ${course.courseName}:`, courseErr.message)
        failed++
      }
    }

    console.log(`✅ [Quiz Scheduler] Done! Generated: ${generated}, Failed: ${failed}`)
  } catch (error) {
    console.log("❌ [Quiz Scheduler] Error:", error.message)
  }
}

// Schedule: Every Sunday at 9:00 AM
// Cron format: second minute hour day month weekday
// 0 9 * * 0 = At 09:00 AM every Sunday
const startQuizScheduler = () => {
  cron.schedule("0 9 * * 0", () => {
    console.log("📅 Sunday 9 AM — Running weekly quiz generation...")
    runWeeklyQuizGeneration()
  })
  console.log("✅ [EduAI Quiz Scheduler] Started — Runs every Sunday at 9 AM")
}

// Export for manual trigger also
module.exports = { startQuizScheduler, runWeeklyQuizGeneration }
